language: python # python3 is the default as of mid 2019
services:
    - docker

before_install:
    - docker build -t autograder -f metatests/Dockerfile .

script:
    - python3 -m unittest discover -s metatests
    - docker run autograder /bin/sh -c "chmod +x source/metatests/integration_test.sh && ./source/metatests/integration_test.sh"
