language: # No language needed, as python is already installed in the autograder docker image
services:
    - docker

before_install:
    - docker build -t autograder -f metatests/Dockerfile .

script:
    - docker run autograder /bin/sh -c "cd /autograder/source && python3 -m unittest discover -v -s metatests"
    - docker run autograder /bin/sh -c "chmod +x source/metatests/integration_test.sh && ./source/metatests/integration_test.sh"
