language: # No language needed, as python is already installed in the autograder docker image

services:
    - docker

before_install:
    - docker build -t autograder -f metatests/Dockerfile .

script:
    - docker run autograder /bin/sh -c "cd /autograder/source && python3 -m unittest discover -v -s metatests"
    - chmod +x metatests/dispatch_integration_tests.sh && ./metatests/dispatch_integration_tests.sh
