#!/usr/bin/env bash

cd /autograder/source

## Pull updates from git
source update.sh

## Copy required files from submission directory to testing directory
python3 copy_files.py

## Run tests and save output
python3 run_tests.py > /autograder/results/results.json
