name: pr-blocking-todos-CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    env:
      LOCAL_BIN_PATH: .github/pr-blocking-todos
      SCRIPT_NAME: checkfortodos.py
      TODOS_FNAME: .pr-blocking-todos.md

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Unit tests for PR-blocking TODOs
        env:
            TEST_DIR_NAME: tests
        run: |
          cd "$LOCAL_BIN_PATH"
          python3 -m unittest discover -v -s "$TEST_DIR_NAME"

      - name: Check for PR-blocking TODOs
        run: |
          python3 "$LOCAL_BIN_PATH/$SCRIPT_NAME" "$TODOS_FNAME"

